# Generated by Django 3.1.2 on 2022-08-31 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20220831_1725'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ajusteStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.CharField(max_length=150, null=True, verbose_name='Observaciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='stock',
            name='detalle',
            field=models.CharField(max_length=150, null=True, verbose_name='Observaciones'),
        ),
        migrations.CreateModel(
            name='detalleAjuste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_nuevo', models.IntegerField()),
                ('id_ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ajustestock')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
