# Generated by Django 3.1.2 on 2022-08-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20220831_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='detalle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Observaciones'),
        ),
    ]
