# Generated by Django 3.1.2 on 2022-08-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20220831_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustestock',
            name='usuario',
            field=models.CharField(max_length=150, verbose_name='Usuarios'),
        ),
        migrations.AlterField(
            model_name='detalleajuste',
            name='stock_nuevo',
            field=models.IntegerField(default=1),
        ),
    ]
