# Generated by Django 3.1.2 on 2022-09-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20220831_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='stockActual',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='usuario',
            field=models.CharField(default=2, max_length=150, verbose_name='Usuarios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='tipoMovimiento',
            field=models.CharField(max_length=50, verbose_name='Tipo Movimiento'),
        ),
    ]
