# Generated by Django 3.1.2 on 2022-09-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20220912_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id_movimiento',
        ),
    ]
