# Generated by Django 3.1.2 on 2022-09-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20220912_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajustestock',
            options={'verbose_name': 'Ajuste Stock', 'verbose_name_plural': 'Ajustes Stocks'},
        ),
        migrations.AlterModelOptions(
            name='historicalajustestock',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Ajuste Stock'},
        ),
        migrations.AddField(
            model_name='stock',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
