# Generated by Django 3.1.2 on 2022-09-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20220912_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajustestock',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='historicalajustestock',
            name='detalle',
        ),
        migrations.AddField(
            model_name='detalleajuste',
            name='detalle',
            field=models.CharField(max_length=150, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='detalleajuste',
            name='motivo',
            field=models.CharField(choices=[['Vencido', 'Vencido'], ['Devolucion', 'Devolucion'], ['Mal estado', 'Mal estado']], default=1, max_length=150),
            preserve_default=False,
        ),
    ]
