# Generated by Django 3.1.2 on 2022-09-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20220914_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleajuste',
            old_name='stock_nuevo',
            new_name='cantidad',
        ),
    ]
