# Generated by Django 3.1.2 on 2022-09-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20220914_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustestock',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalajustestock',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
