# Generated by Django 3.2.14 on 2022-09-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20220914_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('-fecha',), 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
