# Generated by Django 3.1.2 on 2022-10-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_stock_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detalleAjuste',
        ),
    ]
