# Generated by Django 3.1.2 on 2022-10-04 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0014_auto_20220922_1739'),
        ('stock', '0014_delete_detalleajuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustestock',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='detalle',
            field=models.CharField(max_length=150, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='id_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='motivo',
            field=models.CharField(choices=[['Vencido', 'Vencido'], ['Devolucion', 'Devolucion'], ['Mal estado', 'Mal estado']], default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalajustestock',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicalajustestock',
            name='detalle',
            field=models.CharField(max_length=150, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='historicalajustestock',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='producto.producto'),
        ),
        migrations.AddField(
            model_name='historicalajustestock',
            name='motivo',
            field=models.CharField(choices=[['Vencido', 'Vencido'], ['Devolucion', 'Devolucion'], ['Mal estado', 'Mal estado']], default=1, max_length=150),
            preserve_default=False,
        ),
    ]
