# Generated by Django 3.1.2 on 2022-10-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20221004_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajustestock',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='historicalajustestock',
            name='usuario',
        ),
    ]
