# Generated by Django 3.1.2 on 2022-10-04 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0016_auto_20221004_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustestock',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.users', verbose_name='Usuarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalajustestock',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
    ]
