# Generated by Django 3.1.2 on 2022-12-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20221004_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='id_tipo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
