# Generated by Django 3.1.2 on 2022-12-15 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0018_auto_20221127_1939'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0018_stock_id_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustestock',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='ajustestock',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
    ]
