# Generated by Django 3.1.2 on 2022-08-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
    ]
