# Generated by Django 3.1.2 on 2022-09-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20220910_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmarca',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Marca'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
    ]
