# Generated by Django 3.1.2 on 2022-09-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20220910_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='modified_date',
        ),
        migrations.AlterField(
            model_name='marca',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='HistoricalMarca',
        ),
    ]
