# Generated by Django 3.1.2 on 2022-09-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_auto_20220910_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vencimiento',
            field=models.DateField(null=True),
        ),
    ]
