# Generated by Django 3.1.2 on 2022-09-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_producto_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='vencimiento',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
