# Generated by Django 3.1.2 on 2022-09-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_auto_20220920_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='vencimiento',
            field=models.DateField(null=True),
        ),
    ]
