# Generated by Django 3.1.2 on 2022-10-19 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0014_auto_20220922_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPromocion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('fechaInicio', models.DateField(null=True, verbose_name='Fecha Inicio')),
                ('fechaFin', models.DateField(null=True, verbose_name='Fecha Finalizacion')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'verbose_name': 'Producto Promocion',
                'verbose_name_plural': 'Productos Promociones',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductoPromocion',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('fechaInicio', models.DateField(null=True, verbose_name='Fecha Inicio')),
                ('fechaFin', models.DateField(null=True, verbose_name='Fecha Finalizacion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_producto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='producto.producto')),
            ],
            options={
                'verbose_name': 'historical Producto Promocion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
