# Generated by Django 3.1.2 on 2022-10-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0015_historicalproductopromocion_productopromocion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproducto',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
    ]
