# Generated by Django 3.1.2 on 2022-11-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0017_auto_20221102_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproducto',
            name='vencimiento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='vencimiento',
        ),
    ]
