# Generated by Django 3.1.2 on 2022-12-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0018_auto_20221127_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='codigo',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
