# Generated by Django 3.1.2 on 2022-04-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='tipoComprobante',
            field=models.IntegerField(choices=[(0, 'Factura'), (1, 'Recibo'), (2, 'Nota Credito')], verbose_name='Tipo Comprobante'),
        ),
    ]
