# Generated by Django 3.1.2 on 2022-08-20 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20220421_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarjetaCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tarjetaDebito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ventas',
            name='estado',
            field=models.CharField(default='Adeudado', max_length=150),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='tipoComprobante',
            field=models.CharField(choices=[['Factura', 'Factura'], ['Recibo', 'Recibo'], ['Nota Credito', 'Nota Credito']], max_length=50, verbose_name='Tipo Comprobante'),
        ),
        migrations.CreateModel(
            name='formaPagoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto')),
                ('tipoPago', models.IntegerField(choices=[[1, 'Efectivo'], [2, 'Credito'], [3, 'Debito']], verbose_name='Tipo Pago')),
                ('cuotas', models.IntegerField(blank=True, null=True)),
                ('id_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.ventas')),
                ('tipoCredito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.tarjetacredito', verbose_name='Seleccionar Tarjeta')),
            ],
        ),
    ]
