# Generated by Django 3.1.2 on 2022-04-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20220421_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='tipoComprobante',
            field=models.CharField(choices=[['Factura', 'Factura'], ['Recibo', 'Recibo'], ['Nota Credito', 'Nota Credito']], max_length=50, verbose_name='Tipo Comprobante'),
        ),
    ]
