# Generated by Django 3.1.2 on 2022-08-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_formapagoventa_tarjetacredito_tarjetadebito'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagoventa',
            name='estado',
            field=models.CharField(default='Adeudado', max_length=150),
        ),
    ]
