# Generated by Django 3.1.2 on 2022-08-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_formapagoventa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='estado',
            field=models.CharField(default='Adeudado', max_length=150),
        ),
    ]
