# Generated by Django 3.1.2 on 2022-11-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20220912_1937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tarjetaDebito',
        ),
    ]
