# Generated by Django 3.1.2 on 2022-11-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_delete_tarjetadebito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetacredito',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
