# Generated by Django 3.1.2 on 2022-12-15 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_auto_20221127_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagoventa',
            name='tipoCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.tarjetacredito', verbose_name='Seleccionar Tarjeta'),
        ),
    ]
