# Generated by Django 3.1.2 on 2022-12-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0018_auto_20221127_1939'),
        ('clientes', '0001_initial'),
        ('ventas', '0008_auto_20221215_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientes'),
        ),
    ]
