# Generated by Django 3.1.2 on 2021-10-15 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarjetaCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tarjetaDebito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='formaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('credito', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('debito', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cuotas', models.IntegerField(blank=True, null=True)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compras')),
                ('tipoCredito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cedal.tarjetacredito')),
                ('tipoDebito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cedal.tarjetadebito')),
            ],
        ),
    ]
