# Generated by Django 3.1.2 on 2021-12-01 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        ('compras', '0001_initial'),
        ('cedal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapago',
            name='id_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.ventas'),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='id_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.compras'),
        ),
    ]
