# Generated by Django 3.1.2 on 2021-04-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='formaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('credito', models.DecimalField(decimal_places=2, max_digits=8)),
                ('debito', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cuotas', models.IntegerField()),
                ('tipoCredito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedal.tarjetacredito')),
                ('tipoDebito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedal.tarjetadebito')),
            ],
        ),
    ]
