# Generated by Django 3.1.2 on 2022-04-21 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('ventas', '0002_auto_20220421_2024'),
        ('cedal', '0002_auto_20211201_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapago',
            name='id_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.compras'),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='id_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.ventas'),
        ),
    ]
