# Generated by Django 3.1.2 on 2021-04-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_detallecompra_total'),
        ('cedal', '0002_formapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapago',
            name='id_compra',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='compras.compras'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formapago',
            name='credito',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='cuotas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='debito',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='efectivo',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='tipoCredito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cedal.tarjetacredito'),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='tipoDebito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cedal.tarjetadebito'),
        ),
    ]
