# Generated by Django 3.1.2 on 2021-05-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedal', '0003_auto_20210429_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapago',
            name='credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='cuotas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='debito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='tipoCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cedal.tarjetacredito'),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='tipoDebito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cedal.tarjetadebito'),
        ),
    ]
