# Generated by Django 3.1.2 on 2022-07-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedal', '0003_auto_20220421_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formapago',
            old_name='credito',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='formapago',
            name='debito',
        ),
        migrations.RemoveField(
            model_name='formapago',
            name='efectivo',
        ),
    ]
