# Generated by Django 3.1.2 on 2022-07-26 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedal', '0004_auto_20220706_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapago',
            name='tipoCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cedal.tarjetacredito', verbose_name='Seleccionar Tarjeta'),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto'),
        ),
    ]
