# Generated by Django 3.1.2 on 2022-11-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedal', '0006_backup_historicalbackup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'verbose_name': 'Respaldo', 'verbose_name_plural': 'Respaldos'},
        ),
        migrations.AlterModelOptions(
            name='historicalbackup',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Respaldo'},
        ),
    ]
