# Generated by Django 3.1.2 on 2022-11-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedal', '0007_auto_20221109_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='formaPago',
        ),
        migrations.DeleteModel(
            name='tarjetaCredito',
        ),
        migrations.DeleteModel(
            name='tarjetaDebito',
        ),
    ]
