# Generated by Django 3.1.2 on 2022-09-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
