# Generated by Django 3.1.2 on 2022-09-30 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0014_auto_20220922_1739'),
        ('produccion', '0003_delete_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='producto',
        ),
        migrations.AddField(
            model_name='produccion',
            name='cantidad_pedido',
            field=models.IntegerField(default=1, verbose_name='Cantidad Pedido'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='cantidad_retiro',
            field=models.IntegerField(default=1, verbose_name='Cantidad  Retiro'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='estado',
            field=models.CharField(choices=[['Pendiente', 'Pendiente'], ['Producido', 'Producido']], default='Pendiente', max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='producto_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_pedido', to='producto.producto'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='producto_retiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_retiro', to='producto.producto'),
        ),
    ]
