# Generated by Django 3.1.2 on 2022-10-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_auto_20220930_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproduccion',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Produccion'},
        ),
        migrations.AlterModelOptions(
            name='produccion',
            options={'verbose_name': 'Produccion', 'verbose_name_plural': 'Produccion'},
        ),
    ]
