# Generated by Django 3.1.2 on 2022-12-15 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0018_auto_20221127_1939'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produccion', '0006_auto_20221004_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='producto_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_pedido', to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='producto_retiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_retiro', to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
