# Generated by Django 3.1.2 on 2021-10-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cuit', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('condicion', models.IntegerField(choices=[[0, 'Consumidor final'], [1, 'Responsable inscripto']])),
            ],
        ),
    ]
