# Generated by Django 3.1.2 on 2022-12-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Razon Social'),
        ),
    ]
