# Generated by Django 3.1.2 on 2021-04-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cuit',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
