# Generated by Django 3.1.2 on 2022-07-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_caja_id_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='id_compra',
        ),
    ]
