# Generated by Django 3.2.14 on 2022-07-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_remove_caja_id_compra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caja',
            new_name='movCaja',
        ),
    ]
