# Generated by Django 3.1.2 on 2022-07-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_auto_20220727_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
