# Generated by Django 3.1.2 on 2022-12-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_auto_20221218_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterModelOptions(
            name='historicalcaja',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Caja'},
        ),
        migrations.AlterModelOptions(
            name='historicalmovcaja',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Movimiento de Caja'},
        ),
        migrations.AlterModelOptions(
            name='movcaja',
            options={'verbose_name': 'Movimiento de Caja', 'verbose_name_plural': 'Movimientos de cajas'},
        ),
    ]
