# Generated by Django 3.1.2 on 2021-11-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_users_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='nivel',
        ),
        migrations.AddField(
            model_name='users',
            name='group',
            field=models.ManyToManyField(null=True, to='auth.Group'),
        ),
    ]
