# Generated by Django 3.1.2 on 2021-11-09 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211109_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='group',
            new_name='nivel',
        ),
    ]
