# Generated by Django 3.1.2 on 2021-11-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211109_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='nivel',
        ),
    ]
