# Generated by Django 3.1.2 on 2021-04-17 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('iva', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipoComprobante', models.IntegerField(choices=[[0, 'Factura'], [1, 'Recibo'], [2, 'Nota Credito']])),
                ('cuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores')),
            ],
        ),
    ]
