# Generated by Django 3.1.2 on 2022-08-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='estado',
            field=models.CharField(default='Adeudado', max_length=150),
        ),
        migrations.AlterField(
            model_name='compras',
            name='tipoComprobante',
            field=models.CharField(choices=[['Factura', 'Factura'], ['Recibo', 'Recibo'], ['Nota Credito', 'Nota Credito']], max_length=150, verbose_name='Tipo Comprobante'),
        ),
        migrations.CreateModel(
            name='formaPagoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto')),
                ('tipoPago', models.CharField(choices=[['Efectivo', 'Efectivo'], ['Transferencia', 'Transferencia'], ['Cheques', 'Cheques']], max_length=150, verbose_name='Tipo Pago')),
                ('id_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.compras')),
            ],
        ),
    ]
