# Generated by Django 3.1.2 on 2021-04-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campras',
            new_name='Compras',
        ),
    ]
