# Generated by Django 3.1.2 on 2022-07-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20220627_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='estado',
            field=models.CharField(default='Adeudado', max_length=150),
        ),
    ]
