# Generated by Django 3.1.2 on 2022-09-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20220912_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compras',
            options={'ordering': ('-fecha',), 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompras',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Compra'},
        ),
    ]
