# Generated by Django 3.1.2 on 2021-04-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_detallecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8),
            preserve_default=False,
        ),
    ]
