# Generated by Django 3.1.2 on 2022-08-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_formapagocompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapagocompra',
            name='cheques',
        ),
        migrations.RemoveField(
            model_name='formapagocompra',
            name='transferencia',
        ),
        migrations.AddField(
            model_name='formapagocompra',
            name='tipoPago',
            field=models.IntegerField(choices=[[1, 'Efectivo'], [2, 'Transferencia'], [3, 'Cheques']], default=1, verbose_name='Tipo Pago'),
            preserve_default=False,
        ),
    ]
