# Generated by Django 3.1.2 on 2022-11-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20220912_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='estado',
            field=models.CharField(choices=[['Pagado', 'Pagado'], ['Adeudado', 'Adeudado']], default='Adeudado', max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalcompras',
            name='estado',
            field=models.CharField(choices=[['Pagado', 'Pagado'], ['Adeudado', 'Adeudado']], default='Adeudado', max_length=150),
        ),
    ]
