# Generated by Django 3.1.2 on 2021-05-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20210503_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compras',
            options={'ordering': ('-fecha',)},
        ),
    ]
