# Generated by Django 3.1.2 on 2022-11-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20221109_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagocompra',
            name='id_compra',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='compras.compras'),
            preserve_default=False,
        ),
    ]
