# Generated by Django 3.1.2 on 2022-08-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_auto_20220819_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapagocompra',
            name='fecha',
        ),
    ]
