# Generated by Django 3.1.2 on 2022-12-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_auto_20221112_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='comprobante',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcompras',
            name='comprobante',
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
