# Generated by Django 3.1.2 on 2022-12-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20221129_1753'),
        ('producto', '0018_auto_20221127_1939'),
        ('compras', '0007_auto_20221213_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='cuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedores'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto'),
        ),
    ]
