# Generated by Django 3.1.2 on 2022-08-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_remove_formapagocompra_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagocompra',
            name='fecha',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
