# Generated by Django 3.1.2 on 2022-12-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_auto_20221215_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='comprobante',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalcompras',
            name='comprobante',
            field=models.CharField(max_length=8),
        ),
    ]
