# Generated by Django 3.1.2 on 2022-08-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_auto_20220819_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapagocompra',
            name='fecha',
        ),
    ]
