# Generated by Django 3.1.2 on 2022-08-19 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_remove_formapagocompra_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagocompra',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
