# Generated by Django 3.1.2 on 2022-08-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_formapagocompra_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapagocompra',
            name='fecha',
        ),
    ]
