# Generated by Django 3.1.2 on 2022-08-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0016_remove_formapagocompra_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagocompra',
            name='fecha',
            field=models.DateField(auto_now_add=True, default='some string'),
            preserve_default=False,
        ),
    ]
