# Generated by Django 3.1.2 on 2022-08-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0019_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
    ]
